/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package centralLibrary;

import centralLibrary.scenes.BerandaScene;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    private Stage stage;

    public Stage getStage() {
        return stage;
    }

    public void setStage(Stage stage) {
        this.stage = stage;
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        BerandaScene berandaScene =  new BerandaScene(stage);
        berandaScene.berandaScene();
    }
}